services:
  postgres:
    image: postgres
    container_name: myapp-db
    volumes:
      - postgres-data:/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    container_name: myapp-adminer
    restart: always
    ports:
      - 8080:8080
    
volumes:
  postgres-data:
    name: ${POSTGRES_DB_NAME}